version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '12.21'
    steps:
      - checkout
      - node:
          steps:
            - run: npm install
            - run: npm test
            - run: npm build
workflows:
  build-and-test:
    jobs:
      - build-and-test
