version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '12.21'
    steps:
      - checkout
      - node:
          steps:
            - run: yarn install
            - run: yarn test
            - run: yarn build
workflows:
  build-and-test:
    jobs:
      - build-and-test
